AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Parkinson fMRI detection using SageMaker Notebook Instance with GitHub integration'

Parameters:
  NotebookInstanceName:
    Type: String
    Default: 'parkinson-fmri-detector'
    Description: 'Name for the SageMaker notebook instance'
    
  InstanceType:
    Type: String
    Default: 'ml.t3.medium'
    AllowedValues:
      - ml.t3.medium
      - ml.t3.large
      - ml.t3.xlarge
      - ml.m5.large
      - ml.m5.xlarge
      - ml.m5.2xlarge
    Description: 'SageMaker notebook instance type'
    
  BucketName:
    Type: String
    Default: 'fmri-dataset-bucket'
    Description: 'Name for the S3 bucket to store fMRI datasets (must be globally unique)'
    
  GitHubRepository:
    Type: String
    Default: 'https://github.com/vanyaphi/Parkinson-fMRI-detector.git'
    Description: 'GitHub repository URL to clone into the notebook instance'
    
  GitHubUsername:
    Type: String
    Default: ''
    Description: 'GitHub username for private repositories (optional)'
    
  GitHubToken:
    Type: String
    Default: ''
    NoEcho: true
    Description: 'GitHub personal access token for private repositories (optional)'
    
  VolumeSize:
    Type: Number
    Default: 20
    MinValue: 5
    MaxValue: 16384
    Description: 'Size of the EBS volume in GB for the notebook instance'

Conditions:
  HasGitHubCredentials: !And
    - !Not [!Equals [!Ref GitHubUsername, '']]
    - !Not [!Equals [!Ref GitHubToken, '']]

Resources:
  # SageMaker Code Repository
  SageMakerCodeRepository:
    Type: AWS::SageMaker::CodeRepository
    Properties:
      CodeRepositoryName: !Sub '${NotebookInstanceName}-code-repo'
      GitConfig:
        RepositoryUrl: !Ref GitHubRepository
        Branch: main
        SecretArn: !If
          - HasGitHubCredentials
          - !Ref GitHubSecret
          - !Ref AWS::NoValue
      Tags:
        - Key: Purpose
          Value: 'Parkinson fMRI Detection Code'
        - Key: Project
          Value: 'Neuroimaging Research'

  # AWS Secrets Manager secret for GitHub credentials (if provided)
  GitHubSecret:
    Type: AWS::SecretsManager::Secret
    Condition: HasGitHubCredentials
    Properties:
      Name: !Sub '${NotebookInstanceName}-github-secret'
      Description: 'GitHub credentials for SageMaker Code Repository'
      SecretString: !Sub |
        {
          "username": "${GitHubUsername}",
          "password": "${GitHubToken}"
        }
      Tags:
        - Key: Purpose
          Value: 'GitHub Authentication'
        - Key: Project
          Value: 'Parkinson fMRI Detection'
  # S3 Bucket for fMRI datasets
  FMRIDatasetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
      Tags:
        - Key: Purpose
          Value: 'fMRI Dataset Storage'
        - Key: Project
          Value: 'Parkinson Detection'

  # S3 Bucket Policy for secure access
  FMRIDatasetBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FMRIDatasetBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${FMRIDatasetBucket}/*'
              - !GetAtt FMRIDatasetBucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          - Sid: AllowSageMakerAccess
            Effect: Allow
            Principal:
              AWS: !GetAtt SageMakerNotebookRole.Arn
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:ListBucket'
              - 's3:GetBucketLocation'
            Resource:
              - !Sub 'arn:aws:s3:::${FMRIDatasetBucket}/*'
              - !GetAtt FMRIDatasetBucket.Arn

  # IAM Role for SageMaker Notebook Instance
  SageMakerNotebookRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:GetBucketVersioning
                Resource:
                  - !Sub 'arn:aws:s3:::${FMRIDatasetBucket}/*'
                  - !GetAtt FMRIDatasetBucket.Arn
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLocation
                Resource: '*'
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - logs:DescribeLogGroups
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
        - PolicyName: SecretsManagerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: !If
                  - HasGitHubCredentials
                  - !Ref GitHubSecret
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*'
        - PolicyName: CodeRepositoryPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:DescribeCodeRepository
                  - sagemaker:ListCodeRepositories
                Resource: '*'

  # Lifecycle Configuration for auto-shutdown and setup
  NotebookLifecycleConfig:
    Type: AWS::SageMaker::NotebookInstanceLifecycleConfig
    Properties:
      NotebookInstanceLifecycleConfigName: 'fmrinblc'
            
      OnStart:
        - Content: !Base64 |
            #!/bin/bash

            set -ex

            # OVERVIEW
            # This script stops a SageMaker notebook once it's idle for more than 1 hour (default time)
            # You can change the idle time for stop using the environment variable below.
            # If you want the notebook the stop only if no browsers are open, remove the --ignore-connections flag
            #
            # Note that this script will fail if either condition is not met
            #   1. Ensure the Notebook Instance has internet connectivity to fetch the example config
            #   2. Ensure the Notebook Instance execution role permissions to SageMaker:StopNotebookInstance to stop the notebook 
            #       and SageMaker:DescribeNotebookInstance to describe the notebook.
            #

            # PARAMETERS
            IDLE_TIME=3600

            echo "Fetching the autostop script"
            wget https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/master/scripts/auto-stop-idle/autostop.py


            echo "Detecting Python install with boto3 install"

            # Find which install has boto3 and use that to run the cron command. So will use default when available
            # Redirect stderr as it is unneeded
            CONDA_PYTHON_DIR=$(source /home/ec2-user/anaconda3/bin/activate /home/ec2-user/anaconda3/envs/JupyterSystemEnv && which python)
            if $CONDA_PYTHON_DIR -c "import boto3" 2>/dev/null; then
                PYTHON_DIR=$CONDA_PYTHON_DIR
            elif /usr/bin/python -c "import boto3" 2>/dev/null; then
                PYTHON_DIR='/usr/bin/python'
            else
                # If no boto3 just quit because the script won't work
                echo "No boto3 found in Python or Python3. Exiting..."
                exit 1
            fi

            echo "Found boto3 at $PYTHON_DIR"


            echo "Starting the SageMaker autostop script in cron"

            (crontab -l 2>/dev/null; echo "*/5 * * * * $PYTHON_DIR $PWD/autostop.py --time $IDLE_TIME --ignore-connections >> /var/log/jupyter.log") | crontab -
  # SageMaker Notebook Instance
  SageMakerNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Ref NotebookInstanceName
      InstanceType: !Ref InstanceType
      RoleArn: !GetAtt SageMakerNotebookRole.Arn
      VolumeSizeInGB: !Ref VolumeSize
      DefaultCodeRepository: !GetAtt SageMakerCodeRepository.CodeRepositoryName
      LifecycleConfigName: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
      Tags:
        - Key: Purpose
          Value: 'Parkinson fMRI Detection'
        - Key: Project
          Value: 'Neuroimaging Research'
        - Key: AutoShutdown
          Value: 'Enabled'
        - Key: CodeRepository
          Value: !Ref SageMakerCodeRepository

  # Lambda function for S3 setup
  S3SetupFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${NotebookInstanceName}-s3-setup'
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt S3SetupRole.Arn
      Timeout: 60
      Code:
        ZipFile: |
          import boto3
          import json
          import cfnresponse
          
          def lambda_handler(event, context):
              try:
                  if event['RequestType'] == 'Create':
                      s3_client = boto3.client('s3')
                      bucket_name = event['ResourceProperties']['BucketName']
                      
                      files = [
                          ('datasets/controls/README.txt', 'Upload control subject fMRI data here'),
                          ('datasets/patients/README.txt', 'Upload patient fMRI data here'),
                          ('results/README.txt', 'Analysis results will be saved here'),
                          ('models/README.txt', 'Trained models will be saved here')
                      ]
                      
                      for key, body in files:
                          s3_client.put_object(Bucket=bucket_name, Key=key, Body=body)
                      
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                  else:
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                  print(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {})

  # IAM Role for Lambda
  S3SetupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${FMRIDatasetBucket}/*'

  # Custom resource for S3 setup
  S3Setup:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt S3SetupFunction.Arn
      BucketName: !Ref FMRIDatasetBucket

Outputs:
  NotebookInstanceName:
    Description: 'SageMaker Notebook Instance Name'
    Value: !Ref SageMakerNotebookInstance
    Export:
      Name: !Sub '${AWS::StackName}-NotebookInstance'

  NotebookInstanceUrl:
    Description: 'SageMaker Notebook Instance URL'
    Value: !Sub 'https://${SageMakerNotebookInstance}.notebook.${AWS::Region}.sagemaker.aws/tree'
    Export:
      Name: !Sub '${AWS::StackName}-NotebookUrl'

  S3BucketName:
    Description: 'S3 Bucket for fMRI datasets'
    Value: !Ref FMRIDatasetBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3Bucket'

  ExecutionRoleArn:
    Description: 'SageMaker Execution Role ARN'
    Value: !GetAtt SageMakerNotebookRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ExecutionRole'

  CodeRepositoryName:
    Description: 'SageMaker Code Repository Name'
    Value: !GetAtt SageMakerCodeRepository.CodeRepositoryName
    Export:
      Name: !Sub '${AWS::StackName}-CodeRepository'

  GitHubSecretArn:
    Condition: HasGitHubCredentials
    Description: 'GitHub credentials secret ARN'
    Value: !Ref GitHubSecret
    Export:
      Name: !Sub '${AWS::StackName}-GitHubSecret'

  GitHubRepository:
    Description: 'GitHub repository cloned to notebook'
    Value: !Ref GitHubRepository
    Export:
      Name: !Sub '${AWS::StackName}-GitHubRepo'